### ISSUE TITLE
How do I change the color to the sidebar and the bottom bar?

### ISSUE THREAD

**Issue by mkanet** [Jaredk3nt/VSThemeGenerator#1]
I'm not sure where else to ask this question.  I noticed on the Theme Generator website that only the below items were configurable.  Is there a way to change other parts of the VSCode GUI like the sidebar, bottom bar, tab color, etc?

**Comment by Jaredk3nt** [comment]
This package provides a standard set of customizable areas pregrouped to provide a consistent experience for testing out color themes quickly. It does lack in customization by choosing that make things easier for people rather than customizable.

If you are looking to customize your own theme I would suggest the VS Code docs on that topic: https://code.visualstudio.com/api/references/theme-color
